FROM mxnetci/ubuntu1804:cpu-base


ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    r-base-core r-cran-devtools libcairo2-dev libxml2-dev \
    && rm -rf /var/lib/apt/lists/*



COPY install-ci/* /ci/
